from __future__ import annotations

from collections.abc import Callable
from enum import Enum
from typing import TYPE_CHECKING, NamedTuple

from Options import Toggle

if TYPE_CHECKING:
    from .world import NEOTwewyWorld


class NEOTwewyLocationType(Enum):
    ScenarioReward = 0
    Shop = 1
    Dive = 2
    NoiseDrop = 3
    Skill = 4
    Pig = 5


class NEOTwewyLocationData(NamedTuple):
    """Special data container to contain the metadata of each item to make filtering work."""

    id: int
    og_item: str

    region: str
    location_type: NEOTwewyLocationType

    option: str

    combat_pin_only: bool = False
    chance: float = 0.0
    chainable: bool = False
    blue_noise: bool = False
    elements: list[str] = []


SCENARIO_REWARDS: dict[str, NEOTwewyLocationData] = {
    "W1D1 - Minamimoto's Pin": NEOTwewyLocationData(
        1110010,
        "Joli bécot",
        "W1D1",
        NEOTwewyLocationType.ScenarioReward,
        "minamimoto_pin",
        combat_pin_only=True,
    ),
    "W1D1 - Shibuya Hikarie": NEOTwewyLocationData(
        1110020,
        "Firestorm",
        "W1D1",
        NEOTwewyLocationType.ScenarioReward,
        "",
    ),
    "W1D2 - 104/Dogenzaka": NEOTwewyLocationData(
        1120010,
        "Sugar Beam",
        "W1D2'",
        NEOTwewyLocationType.ScenarioReward,
        "",
    ),
    "W1D2 - Dogenzaka/O-EAST": NEOTwewyLocationData(
        1120020,
        "Marvelous Crash",
        "W1D2'",
        NEOTwewyLocationType.ScenarioReward,
        "",
    ),
    "W1D2 - TSUTAYA O-EAST": NEOTwewyLocationData(
        1120030,
        "Azamaru",
        "W1D2'",
        NEOTwewyLocationType.ScenarioReward,
        "",
    ),
    "W1D3 - Scramble/Center": NEOTwewyLocationData(
        1130010,
        "5000 Yen",
        "W1D3'",
        NEOTwewyLocationType.ScenarioReward,
        "",
    ),
    "W1D3 - Center Street": NEOTwewyLocationData(
        1130020,
        "1000 Yen",
        "W1D3'",
        NEOTwewyLocationType.ScenarioReward,
        "",
    ),
    "W1D3 - Scramble (10:50)": NEOTwewyLocationData(
        1130030,
        "Tigre PUNKS",
        "W1D3'",
        NEOTwewyLocationType.ScenarioReward,
        "",
    ),
    "W1D4 - Tipsy Tose Hall": NEOTwewyLocationData(
        1140005,
        "5 FP",
        "W1D4",
        NEOTwewyLocationType.ScenarioReward,
        "",
    ),
    "W1D4 - Shinji-of-Some-Trades Dive": NEOTwewyLocationData(
        1140010,
        "ShoGun・Void",
        "W1D4",
        NEOTwewyLocationType.ScenarioReward,
        "",
    ),
    "W1D4 - Center/Scramble": NEOTwewyLocationData(
        1140020,
        "5000 Yen",
        "W1D4",
        NEOTwewyLocationType.ScenarioReward,
        "",
    ),
    "W1D4 - Seiji-of-Some-Trades Dive": NEOTwewyLocationData(
        1140030,
        "Onimaru",
        "W1D4",
        NEOTwewyLocationType.ScenarioReward,
        "",
    ),
    "W1D4 - Scramble/TOWER RECORDS": NEOTwewyLocationData(
        1140040,
        "Thunder and Lightning",
        "W1D4",
        NEOTwewyLocationType.ScenarioReward,
        "",
    ),
    "W1D4 - Eiji Oji Quest (Item)": NEOTwewyLocationData(
        1140050,
        "1000 Yen",
        "W1D4",
        NEOTwewyLocationType.ScenarioReward,
        "",
    ),
    "W1D4 - Eiji Oji Quest (FP)": NEOTwewyLocationData(
        1140055,
        "5 FP",
        "W1D4",
        NEOTwewyLocationType.ScenarioReward,
        "",
    ),
    "W1D4 - The Don Quest (Item)": NEOTwewyLocationData(
        1140060,
        "Axion",
        "W1D4",
        NEOTwewyLocationType.ScenarioReward,
        "",
    ),
    "W1D4 - The Don Quest (FP)": NEOTwewyLocationData(
        1140065,
        "5 FP",
        "W1D4",
        NEOTwewyLocationType.ScenarioReward,
        "",
    ),
    "W1D4 - Katsuhiko Tanimaru Quest (Item)": NEOTwewyLocationData(
        1140070,
        "1000 Yen",
        "W1D4",
        NEOTwewyLocationType.ScenarioReward,
        "",
    ),
    "W1D4 - Katsuhiko Tanimaru Quest (FP)": NEOTwewyLocationData(
        1140075,
        "5 FP",
        "W1D4",
        NEOTwewyLocationType.ScenarioReward,
        "",
    ),
    "W1D4 - Phone Number Obtained": NEOTwewyLocationData(
        1140080,
        "5000 Yen",
        "W1D4",
        NEOTwewyLocationType.ScenarioReward,
        "",
    ),
    "W1D4 - Vending Machine (Repeat)": NEOTwewyLocationData(
        1140090,
        "5000 Yen",
        "W1D4",
        NEOTwewyLocationType.ScenarioReward,
        "",
    ),
    "W1D1 - Day Cleared": NEOTwewyLocationData(
        1000101,
        "Secret Report No. 1",
        "W1D1",
        NEOTwewyLocationType.ScenarioReward,
        "",
    ),
    "W1D2 - Day Cleared": NEOTwewyLocationData(
        1000102,
        "Secret Report No. 2",
        "W1D2'",
        NEOTwewyLocationType.ScenarioReward,
        "",
    ),
    "W1D3 - Day Cleared": NEOTwewyLocationData(
        1000103,
        "Secret Report No. 3",
        "W1D3'",
        NEOTwewyLocationType.ScenarioReward,
        "",
    ),
    "W1D4 - Day Cleared": NEOTwewyLocationData(
        1000104,
        "Secret Report No. 4",
        "W1D4",
        NEOTwewyLocationType.ScenarioReward,
        "",
    ),
}

SHOP_REWARDS: dict[str, NEOTwewyLocationData] = {
    "TOWER RECORDS SHIBUYA (CD) Track 11": NEOTwewyLocationData(
        202102,
        "(CD) Track 11",
        "W1D4",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "TOWER RECORDS SHIBUYA (CD) Track 8": NEOTwewyLocationData(
        202104,
        "(CD) Track 8",
        "W1D4",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "TOWER RECORDS SHIBUYA (CD) Track 12": NEOTwewyLocationData(
        202105,
        "(CD) Track 12",
        "W1D4",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "TOWER RECORDS SHIBUYA (CD) Track 6": NEOTwewyLocationData(
        202108,
        "(CD) Track 6",
        "W1D4",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "TOWER RECORDS SHIBUYA (CD) Track 18": NEOTwewyLocationData(
        202109,
        "(CD) Track 18",
        "W1D4",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "TOWER RECORDS SHIBUYA (CD) Track 4": NEOTwewyLocationData(
        202115,
        "(CD) Track 4",
        "W1D4",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "TOWER RECORDS SHIBUYA (CD) Track 3": NEOTwewyLocationData(
        202116,
        "(CD) Track 3",
        "W1D4",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "TOWER RECORDS SHIBUYA (CD) Track 13": NEOTwewyLocationData(
        202117,
        "(CD) Track 13",
        "W1D4",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "TOWER RECORDS SHIBUYA (CD) Track 7": NEOTwewyLocationData(
        202118,
        "(CD) Track 7",
        "W1D4",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "TOWER RECORDS SHIBUYA (CD) Track 23": NEOTwewyLocationData(
        202125,
        "(CD) Track 23",
        "W1D4",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "TOWER RECORDS SHIBUYA (CD) Track 24": NEOTwewyLocationData(
        202126,
        "(CD) Track 24",
        "W1D4",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "TOWER RECORDS SHIBUYA (CD) Track 25": NEOTwewyLocationData(
        202127,
        "(CD) Track 25",
        "W1D4",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "TOWER RECORDS SHIBUYA (CD) Track 26": NEOTwewyLocationData(
        202128,
        "(CD) Track 26",
        "W1D4",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "TOWER RECORDS SHIBUYA (CD) Track 28": NEOTwewyLocationData(
        202130,
        "(CD) Track 28",
        "W1D4",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "Taiseido Fighting as a Team": NEOTwewyLocationData(
        200101,
        "Fighting as a Team",
        "W1D3",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "Taiseido Combos": NEOTwewyLocationData(
        200102,
        "Combos",
        "W1D3",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "Taiseido Dodging": NEOTwewyLocationData(
        200103,
        "Dodging",
        "W1D3",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "Taiseido Noise Counterattacks": NEOTwewyLocationData(
        200104,
        "Noise Counterattacks",
        "W1D3",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "Taiseido Elemental Affinities": NEOTwewyLocationData(
        200105,
        "Elemental Affinities",
        "W1D3",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "Taiseido Status Ailments": NEOTwewyLocationData(
        200106,
        "Status Ailments",
        "W1D3",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "Taiseido Experience Points": NEOTwewyLocationData(
        200107,
        "Experience Points",
        "W1D3",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "Taiseido Killing It in Combat": NEOTwewyLocationData(
        200108,
        "Killing It in Combat",
        "W1D3",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "Taiseido Picking Up Pins": NEOTwewyLocationData(
        200112,
        "Picking Up Pins",
        "W1D3",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "Taiseido Evolving Pins": NEOTwewyLocationData(
        200113,
        "Evolving Pins",
        "W1D3",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "Taiseido Pin Decks": NEOTwewyLocationData(
        200117,
        "Pin Decks",
        "W1D4",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "Taiseido Scanning": NEOTwewyLocationData(
        200118,
        "Scanning",
        "W1D4",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "Taiseido Noise Symbols": NEOTwewyLocationData(
        200119,
        "Noise Symbols",
        "W1D4",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "Taiseido Chaining Battles": NEOTwewyLocationData(
        200120,
        "Chaining Battles",
        "W1D4",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "Taiseido Farming FP": NEOTwewyLocationData(
        200127,
        "Farming FP",
        "W1D4",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "Taiseido Emotion Noise: Enraged": NEOTwewyLocationData(
        200128,
        "Emotion Noise: Enraged",
        "W1D4",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "Taiseido Emotion Noise: Somber": NEOTwewyLocationData(
        200129,
        "Emotion Noise: Somber",
        "W1D4",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "Taiseido Emotion Noise: Serene": NEOTwewyLocationData(
        200130,
        "Emotion Noise: Serene",
        "W1D4",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "Taiseido Emotion Noise: Fearful": NEOTwewyLocationData(
        200131,
        "Emotion Noise: Fearful",
        "W1D4",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "Taiseido ShibuPay": NEOTwewyLocationData(
        200132,
        "ShibuPay",
        "W1D4",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "Taiseido Mental Notes": NEOTwewyLocationData(
        200141,
        "Mental Notes",
        "W1D4",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "Taiseido Social Network Skills": NEOTwewyLocationData(
        200142,
        "Social Network Skills",
        "W1D4",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "Taiseido Side Quests": NEOTwewyLocationData(
        200143,
        "Side Quests",
        "W1D4",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "Joli bécot 104 Branch Dazzling Denim Cap": NEOTwewyLocationData(
        200401,
        "Dazzling Denim Cap",
        "W1D3",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "Joli bécot 104 Branch Denim Jacket": NEOTwewyLocationData(
        200404,
        "Denim Jacket",
        "W1D4",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "Joli bécot 104 Branch Open-Shoulder Top": NEOTwewyLocationData(
        200406,
        "Open-Shoulder Top",
        "W1D4",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "Joli bécot 104 Branch Shredded Jeans": NEOTwewyLocationData(
        200408,
        "Shredded Jeans",
        "W1D3",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "Joli bécot 104 Branch Leather Miniskirt": NEOTwewyLocationData(
        200410,
        "Leather Miniskirt",
        "W1D4",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "Joli bécot 104 Branch Golden Lighter (VIP 2)": NEOTwewyLocationData(
        200419,
        "Golden Lighter",
        "W1D4",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "Joli bécot 104 Branch Cherry Bomb": NEOTwewyLocationData(
        200421,
        "Cherry Bomb",
        "W1D3",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "Top o' Topo SHIBUYA Flower Headband": NEOTwewyLocationData(
        200501,
        "Flower Headband",
        "W1D3",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "Top o' Topo SHIBUYA Romantic Blouse": NEOTwewyLocationData(
        200504,
        "Romantic Blouse",
        "W1D3",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "Top o' Topo SHIBUYA Flowy Tulle Skirt": NEOTwewyLocationData(
        200507,
        "Flowy Tulle Skirt",
        "W1D4",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "Top o' Topo SHIBUYA Cropped Pants": NEOTwewyLocationData(
        200508,
        "Cropped Pants",
        "W1D3",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "Top o' Topo SHIBUYA Ribbon Pumps": NEOTwewyLocationData(
        200511,
        "Ribbon Pumps",
        "W1D4",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "Top o' Topo SHIBUYA Comfy Loafers (VIP 2)": NEOTwewyLocationData(
        200513,
        "Comfy Loafers",
        "W1D4",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "Gatto Nero Beret": NEOTwewyLocationData(
        200602,
        "Beret",
        "W1D3",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "Gatto Nero Buckle Sleeve Shirt": NEOTwewyLocationData(
        200603,
        "Buckle Sleeve Shirt",
        "W1D3",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "Gatto Nero Off-the-Shoulder Top": NEOTwewyLocationData(
        200605,
        "Off-the-Shoulder Top",
        "W1D4",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "Gatto Nero Denim Micro-Miniskirt (VIP 2)": NEOTwewyLocationData(
        200607,
        "Denim Micro-Miniskirt",
        "W1D4",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "Gatto Nero Frayed Cargo Pants": NEOTwewyLocationData(
        200609,
        "Frayed Cargo Pants",
        "W1D3",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "Shepherd House 1st Bucket Hat": NEOTwewyLocationData(
        200701,
        "Bucket Hat",
        "W1D3'",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "Shepherd House 1st Sheepy T-Shirt": NEOTwewyLocationData(
        200703,
        "Sheepy T-Shirt",
        "W1D4",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "Shepherd House 1st White Shirt (VIP 2)": NEOTwewyLocationData(
        200706,
        "White Shirt",
        "W1D4",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "Shepherd House 1st Chinos": NEOTwewyLocationData(
        200708,
        "Chinos",
        "W1D3'",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "Shepherd House 1st Slip-ons": NEOTwewyLocationData(
        200714,
        "Slip-ons",
        "W1D3'",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "Shepherd House 1st The Great Magma Escape": NEOTwewyLocationData(
        200717,
        "The Great Magma Escape",
        "W1D3'",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "HOG FANG Flat-Brim Snapback": NEOTwewyLocationData(
        200801,
        "Flat-Brim Snapback",
        "W1D3'",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "HOG FANG Baseball Cap": NEOTwewyLocationData(
        200802,
        "Baseball Cap",
        "W1D3'",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "HOG FANG Wired Hairband": NEOTwewyLocationData(
        200804,
        "Wired Hairband",
        "W1D4",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "HOG FANG Pullover Hoodie": NEOTwewyLocationData(
        200806,
        "Pullover Hoodie",
        "W1D3'",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "HOG FANG Tight Denim Skirt": NEOTwewyLocationData(
        200814,
        "Tight Denim Skirt",
        "W1D4",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "HOG FANG High-top Sneakers": NEOTwewyLocationData(
        200817,
        "High-top Sneakers",
        "W1D3'",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "HOG FANG Chain Necklace (VIP 2)": NEOTwewyLocationData(
        200820,
        "Chain Necklace",
        "W1D4",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "garagara Oversized Beanie": NEOTwewyLocationData(
        201901,
        "Oversized Beanie",
        "W1D4",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "garagara Bohemian T-Shirt": NEOTwewyLocationData(
        201904,
        "Bohemian T-Shirt",
        "W1D4",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "garagara Poncho (VIP 2)": NEOTwewyLocationData(
        201906,
        "Poncho",
        "W1D4",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "garagara Bohemian Pants": NEOTwewyLocationData(
        201908,
        "Bohemian Pants",
        "W1D4",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "garagara Bohemian Sandals": NEOTwewyLocationData(
        201914,
        "Bohemian Sandals",
        "W1D4",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "garagara Hippie Shoulder Bag": NEOTwewyLocationData(
        201920,
        "Hippie Shoulder Bag",
        "W1D4",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "garagara Chain Is Gonna Come": NEOTwewyLocationData(
        201921,
        "Chain Is Gonna Come",
        "W1D4",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "Cony×Cony Peach Blossom": NEOTwewyLocationData(
        202801,
        "Peach Blossom",
        "W1D4",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "Cony×Cony Baby's Breath": NEOTwewyLocationData(
        202806,
        "Baby's Breath",
        "W1D4",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "Cony×Cony Black Camellia": NEOTwewyLocationData(
        202808,
        "Black Camellia",
        "W1D4",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "Cony×Cony Clover": NEOTwewyLocationData(
        202811,
        "Clover",
        "W1D4",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "Cony×Cony Deadly Nightshade": NEOTwewyLocationData(
        202816,
        "Deadly Nightshade",
        "W1D4",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "Tigre PUNKS Studded Tiger Cap": NEOTwewyLocationData(
        202902,
        "Studded Tiger Cap",
        "W1D4",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "Tigre PUNKS Biker Jacket": NEOTwewyLocationData(
        202905,
        "Biker Jacket",
        "W1D4",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "Tigre PUNKS Bondage Pants": NEOTwewyLocationData(
        202911,
        "Bondage Pants",
        "W1D4",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "Tigre PUNKS Studded Boots": NEOTwewyLocationData(
        202915,
        "Studded Boots",
        "W1D4",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "Tigre PUNKS Spiked Wristband": NEOTwewyLocationData(
        202919,
        "Spiked Wristband",
        "W1D4",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "Tigre PUNKS Grin Reaper": NEOTwewyLocationData(
        202923,
        "Grin Reaper",
        "W1D4",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "RyuGu Raven Blossom": NEOTwewyLocationData(
        203501,
        "Raven Blossom",
        "W1D4",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "RyuGu Black-Scarlet Blossom": NEOTwewyLocationData(
        203506,
        "Black-Scarlet Blossom",
        "W1D4",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "RyuGu Lapis Chrysanthemum": NEOTwewyLocationData(
        203508,
        "Lapis Chrysanthemum",
        "W1D4",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "RyuGu Violet-Ebony Foxglove": NEOTwewyLocationData(
        203513,
        "Violet-Ebony Foxglove",
        "W1D4",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "TOKYU HANDS 2F Dazzling Denim Cap": NEOTwewyLocationData(
        201401,
        "Dazzling Denim Cap",
        "W1D3'",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "TOKYU HANDS 2F Flat-Brim Snapback": NEOTwewyLocationData(
        201402,
        "Flat-Brim Snapback",
        "W1D3'",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "TOKYU HANDS 2F Baseball Cap": NEOTwewyLocationData(
        201403,
        "Baseball Cap",
        "W1D3'",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "TOKYU HANDS 2F Beret": NEOTwewyLocationData(
        201404,
        "Beret",
        "W1D3'",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "TOKYU HANDS 1F Shockwave": NEOTwewyLocationData(
        201301,
        "Shockwave",
        "W1D3'",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "TOKYU HANDS 1F Force Rounds": NEOTwewyLocationData(
        201302,
        "Force Rounds",
        "W1D3'",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "TOKYU HANDS 1F Firestorm": NEOTwewyLocationData(
        201303,
        "Firestorm",
        "W1D3'",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "TOKYU HANDS 1F Angelic Kick": NEOTwewyLocationData(
        201304,
        "Angelic Kick",
        "W1D3'",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "TOKYU HANDS 1F Azamaru": NEOTwewyLocationData(
        201305,
        "Azamaru",
        "W1D3'",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "TOKYU HANDS 1F Marvelous Crash": NEOTwewyLocationData(
        201306,
        "Marvelous Crash",
        "W1D3'",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "TOKYU HANDS 1F Joli bécot": NEOTwewyLocationData(
        201311,
        "Joli bécot",
        "W1D3'",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "TOKYU HANDS 3F Rare Metal": NEOTwewyLocationData(
        201501,
        "3x Rare Metal",
        "W1D3'",
        NEOTwewyLocationType.Shop,
        "",
    ),
    "TOKYU HANDS 3F Tektite": NEOTwewyLocationData(
        201502,
        "3x Tektite",
        "W1D3'",
        NEOTwewyLocationType.Shop,
        "",
    ),
}

DIVE_DATA: dict[str, NEOTwewyLocationData] = {
    "Dive [W1D4] @DreamChaser Gold Rank": NEOTwewyLocationData(
        310400,
        "2 FP",
        "W1D4",
        NEOTwewyLocationType.Dive,
        "",
    ),
    "Dive [W1D4] @DreamChaser Silver Rank": NEOTwewyLocationData(
        310410,
        "2 FP",
        "W1D4",
        NEOTwewyLocationType.Dive,
        "",
    ),
    "Dive [W1D4] @DreamChaser Bronze Rank": NEOTwewyLocationData(
        310420,
        "2 FP",
        "W1D4",
        NEOTwewyLocationType.Dive,
        "",
    ),
    "Dive [W1D4] @TrustNoOne Gold Rank": NEOTwewyLocationData(
        310401,
        "2 FP",
        "W1D4",
        NEOTwewyLocationType.Dive,
        "",
    ),
    "Dive [W1D4] @TrustNoOne Silver Rank": NEOTwewyLocationData(
        310411,
        "2 FP",
        "W1D4",
        NEOTwewyLocationType.Dive,
        "",
    ),
    "Dive [W1D4] @TrustNoOne Bronze Rank": NEOTwewyLocationData(
        310421,
        "2 FP",
        "W1D4",
        NEOTwewyLocationType.Dive,
        "",
    ),
    "Dive [W1D4] @RyojiOfAllTradesGold Rank": NEOTwewyLocationData(
        310403,
        "2 FP",
        "W1D4",
        NEOTwewyLocationType.Dive,
        "",
    ),
    "Dive [W1D4] @RyojiOfAllTradesSilver Rank": NEOTwewyLocationData(
        310413,
        "2 FP",
        "W1D4",
        NEOTwewyLocationType.Dive,
        "",
    ),
    "Dive [W1D4] @RyojiOfAllTradesBronze Rank": NEOTwewyLocationData(
        310423,
        "2 FP",
        "W1D4",
        NEOTwewyLocationType.Dive,
        "",
    ),
}

ENEMY_DROPS: dict[str, NEOTwewyLocationData] = {
    "Dixiefrog EASY Drop": NEOTwewyLocationData(
        400007,
        "50 Yen",
        "W1D1",
        NEOTwewyLocationType.NoiseDrop,
        "",
        chance=0.3,
        chainable=True,
    ),
    "Dixiefrog NORMAL Drop": NEOTwewyLocationData(
        400107,
        "100 Yen",
        "W1D1",
        NEOTwewyLocationType.NoiseDrop,
        "",
        chance=0.3,
        chainable=True,
    ),
    "Dixiefrog HARD Drop": NEOTwewyLocationData(
        400207,
        "500 Yen",
        "W1D1",
        NEOTwewyLocationType.NoiseDrop,
        "",
        chance=0.1,
        chainable=True,
    ),
    "Decadraven EASY Drop": NEOTwewyLocationData(
        400004,
        "100 Yen",
        "W1D1",
        NEOTwewyLocationType.NoiseDrop,
        "",
        chance=0.3,
        chainable=True,
    ),
    "Decadraven NORMAL Drop": NEOTwewyLocationData(
        400104,
        "Rapturous Rabbits",
        "W1D1",
        NEOTwewyLocationType.NoiseDrop,
        "",
        chance=0.3,
        chainable=True,
    ),
    "Decadraven HARD Drop": NEOTwewyLocationData(
        400204,
        "500 Yen",
        "W1D1",
        NEOTwewyLocationType.NoiseDrop,
        "",
        chance=0.1,
        chainable=True,
    ),
    "Mosh Grizzly EASY Drop": NEOTwewyLocationData(
        400000,
        "500 Yen",
        "W1D1",
        NEOTwewyLocationType.NoiseDrop,
        "",
        chance=0.4,
        chainable=True,
    ),
    "Mosh Grizzly NORMAL Drop": NEOTwewyLocationData(
        400100,
        "Cold Cony×Cony",
        "W1D1",
        NEOTwewyLocationType.NoiseDrop,
        "",
        chance=0.3,
        chainable=True,
    ),
    "Mosh Grizzly HARD Drop": NEOTwewyLocationData(
        400200,
        "1000 Yen",
        "W1D1",
        NEOTwewyLocationType.NoiseDrop,
        "",
        chance=0.1,
        chainable=True,
    ),
    "Jelly Madchester EASY Drop": NEOTwewyLocationData(
        400013,
        "50 Yen",
        "W1D2",
        NEOTwewyLocationType.NoiseDrop,
        "",
        chance=0.3,
        chainable=True,
    ),
    "Jelly Madchester NORMAL Drop": NEOTwewyLocationData(
        400113,
        "Midaregami",
        "W1D2",
        NEOTwewyLocationType.NoiseDrop,
        "",
        chance=0.6,
        chainable=True,
    ),
    "Jelly Madchester HARD Drop": NEOTwewyLocationData(
        400213,
        "Rare Metal",
        "W1D2",
        NEOTwewyLocationType.NoiseDrop,
        "",
        chance=0.1,
        chainable=True,
    ),
    "Garage Wolf EASY Drop": NEOTwewyLocationData(
        400019,
        "500 Yen",
        "W1D3",
        NEOTwewyLocationType.NoiseDrop,
        "",
        chance=0.4,
        chainable=True,
    ),
    "Garage Wolf NORMAL Drop": NEOTwewyLocationData(
        400119,
        "Just Up Ahead",
        "W1D3",
        NEOTwewyLocationType.NoiseDrop,
        "",
        chance=0.3,
        chainable=True,
    ),
    "Garage Wolf HARD Drop": NEOTwewyLocationData(
        400219,
        "Gust of Gorgeous",
        "W1D3",
        NEOTwewyLocationType.NoiseDrop,
        "",
        chance=0.1,
        chainable=True,
    ),
    "Swing Shark EASY Drop": NEOTwewyLocationData(
        400026,
        "Sugar Beam",
        "W1D4",
        NEOTwewyLocationType.NoiseDrop,
        "",
        chance=0.2,
        chainable=True,
    ),
    "Swing Shark NORMAL Drop": NEOTwewyLocationData(
        400126,
        "Stylish Beam",
        "W1D4",
        NEOTwewyLocationType.NoiseDrop,
        "",
        chance=0.2,
        chainable=True,
    ),
    "Swing Shark HARD Drop": NEOTwewyLocationData(
        400226,
        "Creepy Crystal",
        "W1D4",
        NEOTwewyLocationType.NoiseDrop,
        "",
        chance=0.08,
        chainable=True,
    ),
    "Drum 'n' Stinger (Boss) EASY Drop": NEOTwewyLocationData(
        400044,
        "500 Yen",
        "W1D1",
        NEOTwewyLocationType.NoiseDrop,
        "",
        chance=0.3,
        chainable=True,
        blue_noise=True,
    ),
    "Drum 'n' Stinger (Boss) NORMAL Drop": NEOTwewyLocationData(
        400144,
        "1000 Yen",
        "W1D1",
        NEOTwewyLocationType.NoiseDrop,
        "",
        chance=0.3,
        chainable=True,
        blue_noise=True,
    ),
    "Drum 'n' Stinger (Boss) HARD Drop": NEOTwewyLocationData(
        400244,
        "1000 Yen",
        "W1D1",
        NEOTwewyLocationType.NoiseDrop,
        "",
        chance=0.3,
        chainable=True,
        blue_noise=True,
    ),
    "Emo Puffer (Boss) EASY Drop": NEOTwewyLocationData(
        400033,
        "Rapturous Rabbits",
        "W1D4",
        NEOTwewyLocationType.NoiseDrop,
        "",
        chance=0.4,
        chainable=True,
    ),
    "Emo Puffer (Boss) NORMAL Drop": NEOTwewyLocationData(
        400133,
        "Classical Cacophany",
        "W1D4",
        NEOTwewyLocationType.NoiseDrop,
        "",
        chance=0.4,
        chainable=True,
    ),
    "Emo Puffer (Boss) HARD Drop": NEOTwewyLocationData(
        400233,
        "Blizzard Bunny",
        "W1D4",
        NEOTwewyLocationType.NoiseDrop,
        "",
        chance=0.16,
        chainable=True,
    ),
    "Deep Rivers Societist EASY Drop": NEOTwewyLocationData(
        400067,
        "500 Yen",
        "W1D3'",
        NEOTwewyLocationType.NoiseDrop,
        "",
        chance=0.3,
    ),
    "Deep Rivers Societist NORMAL Drop": NEOTwewyLocationData(
        400167,
        "1000 Yen",
        "W1D3'",
        NEOTwewyLocationType.NoiseDrop,
        "",
        chance=0.4,
    ),
    "Deep Rivers Societist HARD Drop": NEOTwewyLocationData(
        400267,
        "Tsurumaru",
        "W1D3'",
        NEOTwewyLocationType.NoiseDrop,
        "",
        chance=0.2,
    ),
    "Go-go Beringei EASY Drop": NEOTwewyLocationData(
        400073,
        "1000 Yen",
        "W1D2'",
        NEOTwewyLocationType.NoiseDrop,
        "",
        chance=0.4,
        chainable=True,
        blue_noise=True,
    ),
    "Go-go Beringei NORMAL Drop": NEOTwewyLocationData(
        400173,
        "Grin Reaper",
        "W1D2'",
        NEOTwewyLocationType.NoiseDrop,
        "",
        chance=0.4,
        chainable=True,
        blue_noise=True,
    ),
    "Go-go Beringei HARD Drop": NEOTwewyLocationData(
        400273,
        "Grin Reaper",
        "W1D2'",
        NEOTwewyLocationType.NoiseDrop,
        "",
        chance=0.4,
        chainable=True,
        blue_noise=True,
    ),
}

PIG_DATA: dict[str, NEOTwewyLocationData] = {
    "W1D2 - Pig Samba (Dogenzaka)": NEOTwewyLocationData(
        410001,
        "5000 Yen",
        "W1D2'",
        NEOTwewyLocationType.Pig,
        "",
    ),
    "W1D3 - Pig Carol (104 Building)": NEOTwewyLocationData(
        410002,
        "Rare Metal",
        "W1D3",
        NEOTwewyLocationType.Pig,
        "",
        elements=["Fire"],
    ),
    "W1D3 - Pig Samba (Center Street)": NEOTwewyLocationData(
        410003,
        "5 Yen",
        "W1D3'",
        NEOTwewyLocationType.Pig,
        "",
    ),
    "W1D4 - Pig Carol(Tower Records)": NEOTwewyLocationData(
        410004,
        "Rare Metal",
        "W1D4",
        NEOTwewyLocationType.Pig,
        "",
        elements=["Stone"],
    ),
    "W1D4 - Pig Bolero/Mambo (Shibuya Hikarie)": NEOTwewyLocationData(
        410005,
        "Axion",
        "W1D4",
        NEOTwewyLocationType.Pig,
        "",
    ),
}

LOCATION_DATA: dict[str, NEOTwewyLocationData] = SCENARIO_REWARDS | SHOP_REWARDS | DIVE_DATA | ENEMY_DROPS | PIG_DATA

PROGRESSIVE_ELEMENTS: list[str] = [element for data in LOCATION_DATA.values() for element in data.elements]

# Location types to inclusion callable
LOCATION_INCLUSION: dict[NEOTwewyLocationType, Callable[[NEOTwewyWorld], bool | Toggle]] = {
    NEOTwewyLocationType.ScenarioReward: lambda world: True,
    NEOTwewyLocationType.Shop: lambda world: world.options.shops,
    NEOTwewyLocationType.Dive: lambda world: world.options.dive,
    NEOTwewyLocationType.NoiseDrop: lambda world: world.options.noise_drops,
    NEOTwewyLocationType.Skill: lambda world: False,
    NEOTwewyLocationType.Pig: lambda world: world.options.pig_drops,
}
